version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    logging:
      driver: "${MOSQUITTO_LOG_DRIVER:-json-file}"

  esp32_sim:
    build:
      context: .
      dockerfile: ./simulators/esp32_sim/Dockerfile
    container_name: esp32_sim
    volumes:
      - ./shared:/app/simulators/shared:ro
    environment:
      - GROUND_HOST=ground
      - GROUND_PORT=9001
      - RUN_TESTS=0
      - ESP32_SIM_CONFIG=/app/simulators/esp32_sim/config.ini
    depends_on:
      - mosquitto
    logging:
      driver: "${ESP32_SIM_LOG_DRIVER:-json-file}"

  imu_sim:
    build:
      context: .
      dockerfile: simulators/imu_sim/Dockerfile
    container_name: imu_sim
    volumes:
      - ./shared:/app/simulators/shared:ro
    environment:
      - HOST=esp32_sim
      - PORT=9000
      - RUN_TESTS=0
      - DISPLAY=host.docker.internal:0.0
      - MPLBACKEND=TkAgg
    depends_on:
      - mosquitto
    logging:
      driver: "${IMU_SIM_LOG_DRIVER:-json-file}"

  gps_sim:
    build:
      context: .
      dockerfile: simulators/gps_sim/Dockerfile
    container_name: gps_sim
    volumes:
      - ./shared:/app/simulators/shared:ro
    environment:
      - HOST=esp32_sim
      - PORT=9000
      - RUN_TESTS=0
    depends_on:
      - mosquitto
    logging:
      driver: "${GPS_SIM_LOG_DRIVER:-json-file}"

  battery_sim:
    build:
      context: .
      dockerfile: simulators/battery_sim/Dockerfile
    container_name: battery_sim
    volumes:
      - ./shared:/app/simulators/shared:ro
    environment:
      - HOST=esp32_sim
      - PORT=9000
      - RUN_TESTS=0
    depends_on:
      - mosquitto
    logging:
      driver: "${BATTERY_SIM_LOG_DRIVER:-json-file}"

  ground:
    build: ./ground
    container_name: digitaltwin_ground
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - esp32_sim
    logging:
      driver: "${GROUND_LOG_DRIVER:-json-file}"

  hmi_backend:
    build: ./hmi/backend
    container_name: hmi_backend
    ports:
      - "8001:8000"
    environment:
      - MQTT_HOST=mosquitto
    depends_on:
      - mosquitto
    logging:
      driver: "${HMI_BACKEND_LOG_DRIVER:-json-file}"

  hmi_frontend:
    build: ./hmi/frontend
    container_name: hmi_frontend
    ports:
      - "3000:80"
    depends_on:
      - hmi_backend
    logging:
      driver: "${HMI_FRONTEND_LOG_DRIVER:-json-file}"

volumes:
  mosquitto_data:
  mosquitto_log:
