version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  mqtt_recorder:
    build: ./mqtt_recorder
    container_name: mqtt_recorder
    volumes:
      - ./shared:/data
      - ./mqtt_recorder/config.json:/app/config.json:ro
    depends_on:
      - mosquitto

  esp32_sim:
    build:
      context: .
      dockerfile: ./simulators/esp32_sim/Dockerfile
    container_name: esp32_sim
    volumes:
      - ./shared:/app/simulators/shared:ro
    environment:
      - RUN_TESTS=0
      - ESP32_SIM_CONFIG=/app/simulators/esp32_sim/config.ini
    depends_on:
      - mosquitto

  imu_sim:
    build:
      context: .
      dockerfile: simulators/imu_sim/Dockerfile
    container_name: imu_sim
    volumes:
      - ./shared:/app/simulators/shared:ro
    environment:
      - HOST=esp32_sim
      - PORT=9000
      - RUN_TESTS=0
      - DISPLAY=host.docker.internal:0.0
      - MPLBACKEND=TkAgg
    depends_on:
      - mosquitto

  gps_sim:
    build:
      context: .
      dockerfile: simulators/gps_sim/Dockerfile
    container_name: gps_sim
    volumes:
      - ./shared:/app/simulators/shared:ro
    environment:
      - HOST=esp32_sim
      - PORT=9000
      - RUN_TESTS=0
    depends_on:
      - mosquitto

  battery_sim:
    build:
      context: .
      dockerfile: simulators/battery_sim/Dockerfile
    container_name: battery_sim
    volumes:
      - ./shared:/app/simulators/shared:ro
    environment:
      - HOST=esp32_sim
      - PORT=9000
      - RUN_TESTS=0
    depends_on:
      - mosquitto

  radar_sim:
    build:
      context: .
      dockerfile: simulators/radar_sim/Dockerfile
    container_name: radar_sim
    volumes:
      - ./shared:/app/simulators/shared:ro
    environment:
      - RUN_TESTS=0
      - RADAR_SIM_CONFIG=/app/simulators/radar_sim/config.json
    depends_on:
      - mosquitto

  hmi_backend:
    build: ./hmi/backend
    container_name: hmi_backend
    ports:
      - "8001:8000"
    environment:
      - MQTT_HOST=mosquitto
    depends_on:
      - mosquitto

  hmi_frontend:
    build: ./hmi/frontend
    container_name: hmi_frontend
    ports:
      - "3000:80"
    depends_on:
      - hmi_backend

volumes:
  mosquitto_data:
  mosquitto_log:
