version: "3.9"
services:
  # --- Ground Station ---
  ground:
    build: ./ground
    container_name: digitaltwin_ground
    ports:
      - "8000:8000"
    restart: unless-stopped

  # --- Simulators ---
  imu_sim:
    build: ./simulators/imu_sim
    container_name: imu_sim
    environment:
      - HOST=esp32_sim
      - PORT=9000

  gps_sim:
    build: ./simulators/gps_sim
    container_name: gps_sim
    environment:
      - HOST=esp32_sim
      - PORT=9000

  battery_sim:
    build: ./simulators/battery_sim
    container_name: battery_sim
    environment:
      - HOST=esp32_sim
      - PORT=9000

  # --- ESP32 simulator ---
  esp32_sim:
    build: ./simulators/esp32_sim
    container_name: esp32_sim
    environment:
      - GROUND_HOST=ground
      - GROUND_PORT=9001
